require:
  - rubocop-rspec
  - rubocop-performance

inherit_from: .rubocop_todo.yml

# Better syntax for validating that a message should be received
# We use lots of delegation classes so this is better
RSpec/MessageSpies:
  EnforcedStyle: receive

# All spec files are huge blocks, should just ignore them
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
