require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  # Match minimum target version in .ruby-version
  TargetRubyVersion: 3.1.4
  # Display all verbose info on failures to help people triage how to fix
  DisplayCopNames: true
  DisplayStyleGuide: true
  # Enable all NewCops by default (Even new 1.x cops)
  NewCops: enable

Layout/LineLength:
  Max: 140

# Better legibility and code-style
Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']

# Better legibility and code-style
Metrics/MethodLength:
  CountAsOne: ['array', 'hash']

# Better syntax for validating that a message should be received
RSpec/MessageSpies:
  EnforcedStyle: receive
