source 'https://rubygems.org'

gem 'rails', '~> 5.2'
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'humanize'
gem 'byebug'
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'shoulda-matchers'
gem 'rubocop', '~> 0.72.0'
gem 'colorize'
