require 'rails'
require 'action_view/helpers'
require 'singleton'
require 'logger'
require 'colorize'

require_relative 'helpers/all'

require_relative 'enemy'
require_relative 'game_other'
require_relative 'logger'
require_relative 'player'
require_relative 'room'
require_relative 'screen'
require_relative 'version'

require_relative 'combat/all'
require_relative 'classes/all'
require_relative 'items/all'
require_relative 'movement/all'
require_relative 'player/all'
require_relative 'rooms/all'
require_relative 'world/all'
