require 'rails'
require 'action_view/helpers'

require_relative 'enemy'
require_relative 'game_other'
require_relative 'room_controller'
require_relative 'version'

require_relative 'combat/all'
require_relative 'fighter/all'
require_relative 'items/all'
require_relative 'movement/all'
require_relative 'player/all'
require_relative 'rooms/all'
require_relative 'world/all'
