require 'rails'
require 'action_view/helpers'
require 'singleton'
require 'logger'
require 'colorize'

require_relative 'helpers/all'

require_relative 'shit_to_sort_out/enemy'
require_relative 'shit_to_sort_out/game_other'
require_relative 'logger'
require_relative 'shit_to_sort_out/room_top_level'
require_relative 'screen'
require_relative 'version'

require_relative 'combat/all'
require_relative 'classes/all'
require_relative 'items/all'
require_relative 'movement/all'
require_relative 'player/all'
require_relative 'rooms/all'
require_relative 'world/all'
